server:
  port: 7751
spring:
  application:
    name: account-service
  profiles:
    active: @spring.profiles.active@
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    root: INFO