spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

cors:
  allow:
    origins: http://localhost:4953