spring:
  config:
    activate:
      on-profile: test

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: mono-service
    server: http://{ip}:{port}
    title: Mono Service
    version: 0.0.1

website:
  domainName: http://{ip}:{port}

