spring:
  config:
    activate:
      on-profile: dev

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: mono-service
    server: http://localhost:8181
    title: Mono Service
    version: 0.0.1

website:
  domainName: http://localhost:8500

