spring:
  application:
    name: mono-service
  profiles:
    active: @spring.profiles.active@
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8181

logging:
  level:
    root: INFO